#!/bin/sh


docker build -f Dockerfile_alpine_build -t golang-alpine-builder .
set -e

DIR=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)

docker run --rm -v ${DIR}:/go/src/slack8s -w /go/src/slack8s golang-alpine-builder sh -c "go get; go build"
