#!/bin/sh

set -e

docker pull golang:1.7.1-alpine

DIR=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)

docker run --rm -v ${DIR}:/go/src/slack8s -w /go/src/slack8s golang:1.7.1-alpine sh -c "apk add --no-cache git; go get; go build"
